### ISSUE TITLE
[QST] How can I choose `enum_type_list` axis values at runtime?

### ISSUE THREAD

**Issue by GregoryKimball** [NVIDIA/nvbench#137]
We have several cuDF benchmarks for which I would like to run one value of an nvbench `enum_type_list` by default, and also be able to access the other values at runtime. 

In this case for [parquet_reader_input](https://github.com/rapidsai/cudf/blob/branch-23.08/cpp/benchmarks/io/parquet/parquet_reader_input.cpp), how can I write `BM_parquet_read_data` so that it only runs `cudf::io::io_type::DEVICE_BUFFER` by default and also `--axis io=HOST_BUFFER` would work at runtime?

I see the nvbench example in [enums.cu](https://github.com/NVIDIA/nvbench/blob/main/examples/enums.cu) - is the recommendation to convert the `NVBENCH_TYPE_AXES` into a `string_axis`?

**Comment by senior-zero** [comment]
Hello @GregoryKimball! 

I'm [using](https://github.com/NVIDIA/cccl/blob/5161b5e92b0cb3f4e86b60ed6aaadbc48aa20cb4/cub/benchmarks/bench/radix_sort/keys.cu#L229) a string axis for enums and then [converting](https://github.com/NVIDIA/cccl/blob/5161b5e92b0cb3f4e86b60ed6aaadbc48aa20cb4/cub/benchmarks/bench/radix_sort/keys.cu#L153C37-L153C37) the string to enum value. This is needed because the benchmark accepts many enum values. For your case, there might be only two values, so using an integer axis might be preferable:
```cpp
void bench(nvbench::state &state)
{
  cuio_source_sink_pair(state.get_int64("IsDeviceBuffer") ? io_type::DEVICE_BUFFER
                                                          : io_type::HOST_BUFFER);
  // ...
}
NVBENCH_BENCH(bench)
  .add_int64_axis("IsDeviceBuffer", {1});
```

**Comment by GregoryKimball** [comment]
Thank you @senior-zero, we will consider switching to string axes for our cuIO benchmarks. I'll close this issue, but if anyone else has thoughts on this topic - I would love to learn from your response as well!
