### ISSUE TITLE
[FEA] Support templated fixture tests

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/nvbench#24]
All cudf benchmarks use templated fixture tests to handle rmm memory pool allocation/deallocation. It will be great if this functionality can be supported by nvbench.

**Comment by karthikeyann** [comment]
We can relax the constraint about templates. The fixture does not need to be templated for cudf.
Most benchmarks are templated benchmark functions with non-templated fixture.
AFAIK, templated-fixture is written for some benchmarks because google benchmark does not support templated benchmarks with non-templated fixture yet.

**Comment by jrhemstad** [comment]
Superseded by https://github.com/NVIDIA/nvbench/issues/77
